---
abstract: 'yet another deployment tool'
author:
  - 'Tokuhiro Matsuno and Archer comitters.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.03'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archer
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  File::Rsync: 0
  MySQL::Diff: 0
  SVN::Agent: 0
requires:
  Carp: 0
  File::HomeDir: 0
  File::Spec: 0
  File::Util: 0
  FindBin: 0
  Getopt::Long: 0
  IO::Prompt: 0
  Kwalify: 0
  List::MoreUtils: 0
  Module::Build: 0
  Net::SSH: 0
  Parallel::ForkManager: 0
  Path::Class: 0
  Pod::Usage: 0
  Storable: 0
  String::CamelCase: 0
  Template: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  Test::More: 0
  UNIVERSAL::require: 0
  YAML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
